### ISSUE TITLE
Cannot find resource Innofactor.Crm.Shuffle.Resource.ShuffleDefinition.xsd

### ISSUE THREAD

**Issue by Miesjh** [Innofactor/Innofactor.Crm.CI#20]
When I press 'Do the shuffle' in the Shuffle Builder, I get the following error: Cannot find resource Innofactor.Crm.Shuffle.Resource.ShuffleDefinition.xsd.

XML: 
`<DataBlock Name="Contacts" Entity="contact" Type="Entity">
  <Export>
    <Attributes>
      <Attribute />
    </Attributes>
  </Export>
</DataBlock>`

**Comment by imranakram** [comment]
This seems to be already resolved. Closing for now. Please let us know if it's still an issue
