### ISSUE TITLE
New version based on open sourced utils

### ISSUE THREAD

**Issue by imranakram** [Innofactor/Innofactor.Crm.CI#23]
Replace the DevUtils nuget with the new Xrm.Utils (https://github.com/Innofactor/Xrm.Utils) project to make it fully open source. Work is in progress already in the `features/utils` branch

**Comment by rappen** [comment]
Love the initiative!
Let me know if I can help in any way.

**Comment by imranakram** [comment]
@rappen One requirement is to support the login via Service Principal for tenants with mandatory MFA login for instance. This requires new parameters such as AppId, Secret Key, Uri of the environment. That needs to be sorted out with the old Connection String parameter that is mandatory at the moment in `XrmCmdletBase` class. Now it wouldn't be a mandatory required for either one of these two options. Wondering how that could be handled in the best way

**Comment by rappen** [comment]
Bottom section [here](https://www.xrmtoolbox.com/documentation/for-users/connecting-to-an-organization/) does not help?

**Comment by imranakram** [comment]
In our tenant where MFA is strictly enforced without exception, this doesn't work either. The system still seems to treat this as a ws-protocol request. What worked here is this implementation in XrmToolBox. This one uses a service principal which is mapped to a program user in CRM. 

![image](https://user-images.githubusercontent.com/13014005/75795055-0503a000-5d72-11ea-8125-86415ea5e02b.png)

**Comment by imranakram** [comment]
This format works fine for connection strings on environments with full MFA enforcement

```
AuthType=ClientSecret;
  url=https://contosotest.crm.dynamics.com;
  ClientId={AppId};
  ClientSecret={ClientSecret}
```
