### ISSUE TITLE
Cannot find resource Innofactor.Crm.Shuffle.Resources.ShuffleDefinition.xsd

### ISSUE THREAD

**Issue by seefernando** [Innofactor/Innofactor.Crm.CI#6]
When trying to import records, I get the the following log entry: "Cannot find resource Innofactor.Crm.Shuffle.Resources.ShuffleDefinition.xsd"  Then nothing seems to happen, no records are imported or failed.
![image](https://user-images.githubusercontent.com/6138858/35020404-e1c76176-faf9-11e7-952b-923cb8b22c61.png)

I'm using the latest plugin from the release section and the latest version of XRM Toolbox and V9.0 Dynamics.

Did I miss something to install the plugin?

[JanFebContentSnippet.zip](https://github.com/Innofactor/Innofactor.Crm.CI/files/1637374/JanFebContentSnippet.zip)

**Comment by rappen** [comment]
Hi - the warning about the xsd file does not "look good", but it is not a problem. It is an internal message that should not be displayed in this case.
The problem with the import is that the definition file does not contain any import statement.

Sample with import:
```
<ShuffleDefinition>
  <Blocks>
    <DataBlock Name="adx_contentsnippet" Entity="adx_contentsnippet" Type="Entity">
      <Export>
        <Filter Attribute="modifiedon" Operator="LastXHours" Type="int" Value="1" />
        <Attributes>
          <Attribute Name="adx_contentsnippetid" IncludeNull="false" />
          <Attribute Name="adx_contentsnippetlanguageid" IncludeNull="false" />
          <Attribute Name="adx_display_name" IncludeNull="false" />
          <Attribute Name="adx_type" IncludeNull="false" />
          <Attribute Name="adx_value" IncludeNull="false" />
          <Attribute Name="adx_websiteid" IncludeNull="false" />
          <Attribute Name="statecode" IncludeNull="false" />
          <Attribute Name="statuscode" IncludeNull="false" />
          <Attribute Name="adx_name" IncludeNull="false" />
        </Attributes>
      </Export>
      <Import CreateWithId="false" Save="CreateUpdate" UpdateInactive="false" UpdateIdentical="false">
        <Match>
          <Attribute Name="adx_websiteid" Display="" />
          <Attribute Name="adx_name" Display="" />
        </Match>
      </Import>
    </DataBlock>
  </Blocks>
</ShuffleDefinition>
```

**Comment by seefernando** [comment]
Worked like a charm!  

Is there anything I can do/provide to help with the missing resource?

**Comment by rappen** [comment]
Great :)
No, thanks. We just have to suppress that message better...
