### ISSUE TITLE
Connection not established. Last CRM error message: Unable to Login to Dynamics CRMOrganizationServiceProxy is null

### ISSUE THREAD

**Issue by seefernando** [Innofactor/Innofactor.Crm.CI#7]
When using the VSTS export task a connection can not be made and the following error is thrown:

`2018-01-17T15:39:29.3492395Z ##[error]Connection not established. Last CRM error message:
Unable to Login to Dynamics CRMOrganizationServiceProxy is null`

I used the same Connection String for both this task as well as Wael's Ping CRM Task:
`AuthType=Office365;Username=$(SourceUsername);Url=https://$(SourceDomain).crm.dynamics.com;Password=$(SourcePassword)`

![image](https://user-images.githubusercontent.com/6138858/35060977-d7ad5b34-fb8d-11e7-9823-29204d80a4a5.png)

Using Hosted VS2017 agent.

**Comment by rappen** [comment]
That is strange....
Can you try running it again with ``system.debug = true`` ?

![image](https://user-images.githubusercontent.com/2572253/35066204-1f7b2c24-fbd0-11e7-8168-518829d68f0a.png)

**Comment by seefernando** [comment]
Thanks for a fast responses!  I'm totally new to devops with CRM so I really appreciate your efforts!
Question, should the shuffle data file be define as part of the export task in my build?  My assumption is no, as the build task will need to get this during the build?
![image](https://user-images.githubusercontent.com/6138858/35069999-eb2f9ac0-fba9-11e7-9270-71b985d662e7.png)


Here is the debug log, I included both Wael's ping and the export task:
[debug_JanFeb.txt](https://github.com/Innofactor/Innofactor.Crm.CI/files/1640776/debug_JanFeb.txt)

**Comment by rappen** [comment]
The data file only has to be set if you want to specify other output file name than default. Default would in your case be ``JanFebContentSnippet.data.xml``

Still don't really understand connectivity problems. Could you contact me off air to discuss connection? Email jonas dot rapp at innofactor dot com.

**Comment by seefernando** [comment]
The issue disappears when using the Hosted agent vs Hosted VS2017

**Comment by rappen** [comment]
This issue should now be solved for all agents by commit https://github.com/Innofactor/Innofactor.Crm.CI/commit/6abf29b99707815d67167d30078a1b81b7607292.
