### ISSUE TITLE
Make appending prefix with "_" and "/" optional 

### ISSUE THREAD

**Issue by tomaswalander** [Innofactor/Innofactor.Crm.CI#8]
First let me say I'm so happy that you decided to release this! I've been looking for quite some time for an improved CI flow for our dynamics development at work. And after reading your blog posts last fall I was on the verge of building something similar on my own until I realized a week ago that you actually released it! Good job! :D 

However, there are some config options that I believe are a hustle IMHO. For webresources you are required to add a prefix. Which makes sense I guess since a "publisher" in the crm has a prefix used for anything it creates. However, the prefix is then appended with an underscore (if not already present) and also a forward slash. This seems a bit odd to be honest. 

E.g., we use webpack to build our css and js code and end up with the following files (names obscured)
ourprefix_library.js -> webresource: ourprefix_library
ourprefix_style.css -> webresource: ourprefix_style
ourprefix_ourcustomapp_js.js -> webresource: ourprefix_ourcustomapp_js
ourprefix_ourcustomapp_html.html  -> webresource: ourprefix_ourcustomapp_html

But trying to configuring the webresource update build task using "ourprefix_" as prefix setting does not work since it also appends a slash meaning it will look for webresources named "ourprefix_/library" etc. 
Moreover, it should probably strip file extensions from the local file names before looking for the webresource. 

As far as I can tell the issue is here. 
https://github.com/Innofactor/Innofactor.Crm.CI/blob/3a8849850266019df62d42a05c89dd0a2080629a/CI/WebResources/UpdateCrmWebResoucesCmdlet.cs#L199

I can definitely make a pull request if you guys think this request makes sense!

**Comment by rappen** [comment]
First let me say Thanks :)

The reason behind the current implementation is the best practice MS has announced to structure your webresources like:
```
pref_/images/myicon.png
pref_/scripts/myscript.js
pref_/content/mypage.html
```
etc.

But I feel your pain, and recently came across a situation where we needed to override this behavior.
I would gladly accept a PR, as long as there is a way to keep it backward compatible. I don't really have the time at this point to come up with a good solution for this, perhaps it would be enough with a flag/bool/checkbox to ``Override best practice folder structure" or similar.

**Comment by tomaswalander** [comment]
Thanks for your quick reply! 

Actually, I didn't know about the naming convention for webresources. I'm normally a front-end developer and quite new to the Dynamics platform. So I guess it makes a lot of sense how you decided to build it. :) 

Anyway, I might look into doing a PR anyway just because I'd like to contribute and I think it would be nice to be able to configure more freely. And I competely agree that it should be backwards compatible. 

Thanks again! :)
